apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  selector:
    matchLabels:
      app: front
  replicas: 2
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: ricardo2000/front:2.0
          ports:
            - containerPort: 80

---
apiVersion: v1 # Kubernetes API version
kind: Service
metadata: # Metadata of the resource kind we are creating
  name: front
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80 # The port that the service is running on in the cluster
      targetPort: 80 # The port exposed by the service
  type: LoadBalancer # type of the service. gai loadbalancer

